spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.17.230:3306/study
    password: 5211
    username: root
  mail:
    # 163邮箱的地址为smtp.163.com，直接填写即可
    host: smtp.163.com
    # 你申请的163邮箱
    username: 19989150208@163.com
    # 注意密码是在开启smtp/pop3时自动生成的，记得保存一下，不然就找不到了
    password: ACVPKFIIEZSOKYHA
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

server:
  port: 8081